In [2]:
import xport.v56

with open('/Users/bblais/Downloads/CARB_E.XPT', 'rb') as f:
    library = xport.v56.load(f)

In [4]:
library.sas_version

'9.3'

In [5]:
import pandas

In [6]:
pandas.__version__

'1.0.1'

In [7]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


/Users/bblais/opt/anaconda3/lib/python3.7/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['f']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [8]:
a=array([1,2,3,4])

In [9]:
a

array([1, 2, 3, 4])

In [11]:
a.dtype

dtype('int64')

In [12]:
a[2]=2.3

In [13]:
a

array([1, 2, 2, 4])

In [14]:
a.dtype

dtype('int64')

In [15]:
a.dtype=float

In [16]:
a

array([5.e-324, 1.e-323, 1.e-323, 2.e-323])

In [17]:
a=array([1,2,3,4])

In [18]:
a=array(a,float)

In [19]:
a

array([1., 2., 3., 4.])

In [20]:
a[2]=2.3

In [21]:
a

array([1. , 2. , 2.3, 4. ])

In [22]:
a.astype(int)

array([1, 2, 2, 4])

In [23]:
a

array([1. , 2. , 2.3, 4. ])